version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
  client-app:
    build: ./une-cinema-react
    environment:
      - REACT_APP_PROXY_HOST=http://server-app:8080
    volumes:
      - ./une-cinema-react/src:/une-cinema-react/src
      - ./une-cinema-react/public:/une-cinema-react/public
    ports:
      - 3000:3000
  server-app:
    build: ./une-cinema-service
    environment:
      - dbURI=mongodb://mongo-db:27017
    volumes:
      - ./une-cinema-service/src:/une-cinema-service/src
    ports:
      - 8080:8080